baseurl: /twitter-archives

plugins:
  - jekyll-optional-front-matter
  - jekyll-commonmark-ghpages

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
